server:
  port: 9001

spring:
  application:
    name: user-service

    

  datasource:
      url: jdbc:mysql://localhost:3306/user_service
      driver-class-name: com.mysql.cj.jdbc.Driver
      username: root
      password: root
  jpa:
      hibernate.ddl-auto: update
      properties:
         hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect 
#
#eureka:
#  client:
#      enabled: true
 