spring:
  application:
    name: config-server
    
  cloud:
    config:
      server:
        git:
          uri: https://github.com/syed25041996/user-contact-config.git
          username: syed25041996
          password: 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
          clone-on-start: true
          
          
server:
  port: 8888
